### ISSUE TITLE
切换合约地址

### ISSUE THREAD

**Issue by lychees** [carboclan/Uniscam#16]
前端代码 copy 这里吧。。
https://github.com/KodamaSakuno/uniswap-interface

切换合约到 BSC 测试网（最好之后其它几个网也能运行）
Factory:
https://testnet.bscscan.com/address/0x53db549ba3e80104f1a8f449133c2ee8d453ab1a#code
Route02:
https://testnet.bscscan.com/address/0xa051966f823def0433ac9ea84b0c5efba5011a08#code

**Comment by nekomeowww** [comment]
Close
refer to repos:

https://github.com/nekomeowww/uniscam-interface
https://github.com/nekomeowww/uniscam-sdk
https://github.com/nekomeowww/uniscam-contract

**Comment by lychees** [comment]
新 Factory 合约：
https://testnet.bscscan.com/address/0xfb75d28518728c2a7046fdc952eef33dfec92289#code
测试用 yUSDT 合约：
https://testnet.bscscan.com/address/0x7ef673c4f262db48af1d2a4a324565f9ff8c0219
